[[language]]
name = "typescript"
auto-format = true
file-types = ["ts"]
language-server = { command = "typescript-language-server", args = ["--stdio"] }
formatter = { command = "node_modules/.bin/prettier", args = ["--parser", "typescript"] }
